# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudmechanic < Formula
  desc "An OBD scanner for your AWS environment. Find cost leaks and security vulnerabilities in seconds."
  homepage "https://github.com/cloudmechanic-cli/cloudmechanic"
  version "1.6.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudmechanic-cli/cloudmechanic/releases/download/v1.6.2/cloudmechanic_1.6.2_darwin_amd64.tar.gz"
      sha256 "686c3f0f4207b17fdeaba75d64c53c9d212fadad34a9612c0dd9b8bea9550d12"

      define_method(:install) do
        bin.install "cloudmechanic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudmechanic-cli/cloudmechanic/releases/download/v1.6.2/cloudmechanic_1.6.2_darwin_arm64.tar.gz"
      sha256 "d239fdcabc3090e96fd7ba372cf341ab3ddab7cf0aaa8dcc177657fff5590765"

      define_method(:install) do
        bin.install "cloudmechanic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudmechanic-cli/cloudmechanic/releases/download/v1.6.2/cloudmechanic_1.6.2_linux_amd64.tar.gz"
      sha256 "6ee7d4098c774190cec5603cf80515e66b76ab9e64f7f47a7b70bb2237468891"
      define_method(:install) do
        bin.install "cloudmechanic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudmechanic-cli/cloudmechanic/releases/download/v1.6.2/cloudmechanic_1.6.2_linux_arm64.tar.gz"
      sha256 "143c633549b63baa268f2a708cea1b5170e02309b6eb1ee1cbe352fd3ec4c930"
      define_method(:install) do
        bin.install "cloudmechanic"
      end
    end
  end

  test do
    system "#{bin}/cloudmechanic", "--help"
  end
end
