# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudmechanic < Formula
  desc "An OBD scanner for your AWS environment. Find cost leaks and security vulnerabilities in seconds."
  homepage "https://github.com/cloudmechanic-cli/cloudmechanic"
  version "1.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudmechanic-cli/cloudmechanic/releases/download/v1.7.1/cloudmechanic_1.7.1_darwin_amd64.tar.gz"
      sha256 "0a3702f47391fd9d40123bdfa5aa777528aa0e045ef55ec1b072be48ebdc4344"

      define_method(:install) do
        bin.install "cloudmechanic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudmechanic-cli/cloudmechanic/releases/download/v1.7.1/cloudmechanic_1.7.1_darwin_arm64.tar.gz"
      sha256 "faa7ec18212b4ead26f3b16526539041ecb047c3363775c723e4917701251ece"

      define_method(:install) do
        bin.install "cloudmechanic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudmechanic-cli/cloudmechanic/releases/download/v1.7.1/cloudmechanic_1.7.1_linux_amd64.tar.gz"
      sha256 "78396e524db4a141564e1116e1cdb4187d213bd15f54e94753a99ac01ffe3779"
      define_method(:install) do
        bin.install "cloudmechanic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudmechanic-cli/cloudmechanic/releases/download/v1.7.1/cloudmechanic_1.7.1_linux_arm64.tar.gz"
      sha256 "372275da9912c52ad1e5fba86d3534131506770c0ff320a0c13e5a4e916e471c"
      define_method(:install) do
        bin.install "cloudmechanic"
      end
    end
  end

  test do
    system "#{bin}/cloudmechanic", "--help"
  end
end
